//HintName: Sample.Connection_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Connection_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding[] ctorParamBindings = null!;

        public Connection_CompiledBinding()
            : base("Sample.Connection", "members/Sample.Connection", false, typeof(global::Sample.Connection))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            var bindings = new global::Stiletto.Internal.Binding[1];
            bindings[0] = resolver.RequestBinding("@primary/Sample.Endpoint", "Sample.Connection::.ctor", true, true)!;
            this.ctorParamBindings = bindings;
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            injectDependencies.UnionWith(this.ctorParamBindings);
        }

        public override object Get()
        {
            return new global::Sample.Connection(
                (global::Sample.Endpoint)this.ctorParamBindings[0].Get()
            );
        }
    }
}
