//HintName: Sample.Roaster_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Roaster_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding[] ctorParamBindings = null!;

        public Roaster_CompiledBinding()
            : base("Sample.Roaster", "members/Sample.Roaster", false, typeof(global::Sample.Roaster))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            var bindings = new global::Stiletto.Internal.Binding[3];
            bindings[0] = resolver.RequestBinding("System.Collections.Generic.IList`1<Sample.Bean>", "Sample.Roaster::.ctor", true, true)!;
            bindings[1] = resolver.RequestBinding("System.Lazy`1<Sample.Bean>", "Sample.Roaster::.ctor", true, true)!;
            bindings[2] = resolver.RequestBinding("Stiletto.IProvider`1<Sample.Bean>", "Sample.Roaster::.ctor", true, true)!;
            this.ctorParamBindings = bindings;
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            injectDependencies.UnionWith(this.ctorParamBindings);
        }

        public override object Get()
        {
            return new global::Sample.Roaster(
                (global::System.Collections.Generic.IList<global::Sample.Bean>)this.ctorParamBindings[0].Get(),
                (global::System.Lazy<global::Sample.Bean>)this.ctorParamBindings[1].Get(),
                (global::Stiletto.IProvider<global::Sample.Bean>)this.ctorParamBindings[2].Get()
            );
        }
    }
}
