//HintName: Rootless_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
[global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
[global::System.Runtime.CompilerServices.CompilerGenerated]
internal sealed class Rootless_CompiledBinding : global::Stiletto.Internal.Binding
{
    public Rootless_CompiledBinding()
        : base("Rootless", "members/Rootless", false, typeof(global::Rootless))
    {
    }

    public override void Resolve(global::Stiletto.Internal.Resolver resolver)
    {
    }

    public override void GetDependencies(
        global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
        global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
    {
    }

    public override object Get()
    {
        return new global::Rootless();
    }
}
