//HintName: Sample.CoffeeMaker_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class CoffeeMaker_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding[] ctorParamBindings = null!;

        public CoffeeMaker_CompiledBinding()
            : base("Sample.CoffeeMaker", "members/Sample.CoffeeMaker", false, typeof(global::Sample.CoffeeMaker))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            var bindings = new global::Stiletto.Internal.Binding[1];
            bindings[0] = resolver.RequestBinding("Sample.Pump", "Sample.CoffeeMaker::.ctor", true, true)!;
            this.ctorParamBindings = bindings;
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            injectDependencies.UnionWith(this.ctorParamBindings);
        }

        public override object Get()
        {
            return new global::Sample.CoffeeMaker(
                (global::Sample.Pump)this.ctorParamBindings[0].Get()
            );
        }
    }
}
