//HintName: Sample.Pump_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Pump_CompiledBinding : global::Stiletto.Internal.Binding
    {
        public Pump_CompiledBinding()
            : base("Sample.Pump", "members/Sample.Pump", false, typeof(global::Sample.Pump))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
        }

        public override object Get()
        {
            return new global::Sample.Pump();
        }
    }
}
