//HintName: Stiletto.Generated.CompiledLoader.g.cs
// <auto-generated/>
#nullable enable
namespace Stiletto.Generated
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class CompiledLoader : global::Stiletto.Internal.ILoader
    {
        public global::Stiletto.Internal.Binding GetInjectBinding(string key, string className, bool mustBeInjectable)
        {
            switch (className)
            {
                case "Sample.Connection": return new global::Sample.Connection_CompiledBinding();
                case "Sample.Endpoint": return new global::Sample.Endpoint_CompiledBinding();
                default: return null!;
            }
        }

        public global::Stiletto.Internal.RuntimeModule GetRuntimeModule(global::System.Type moduleType, object? moduleInstance)
        {
            switch (moduleType.FullName)
            {
                default: return null!;
            }
        }

        public global::Stiletto.Internal.Binding GetLazyInjectBinding(string key, object? requiredBy, string lazyKey) => null!;
        public global::Stiletto.Internal.Binding GetIProviderInjectBinding(string key, object? requiredBy, bool mustBeInjectable, string providerKey) => null!;
    }

    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal static class CompiledLoaderRegistration
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Register() => global::Stiletto.LoaderRegistry.Register(new CompiledLoader());
    }
}
