//HintName: Sample.DerivedInjectable_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class DerivedInjectable_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding baseTypeBinding = null!;

        public DerivedInjectable_CompiledBinding()
            : base("Sample.DerivedInjectable", "members/Sample.DerivedInjectable", false, typeof(global::Sample.DerivedInjectable))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            this.baseTypeBinding = resolver.RequestBinding("members/Sample.BaseInjectable", "members/Sample.DerivedInjectable", false, false)!;
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            propertyDependencies.Add(this.baseTypeBinding);
        }

        public override void InjectProperties(object target)
        {
            var inject = (global::Sample.DerivedInjectable)target;
            this.baseTypeBinding.InjectProperties(inject);
        }

        public override object Get()
        {
            var result = new global::Sample.DerivedInjectable();
            this.InjectProperties(result);
            return result;
        }
    }
}
