//HintName: Sample.Cache_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Cache_CompiledBinding : global::Stiletto.Internal.Binding
    {
        public Cache_CompiledBinding()
            : base("Sample.Cache", "members/Sample.Cache", true, typeof(global::Sample.Cache))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
        }

        public override object Get()
        {
            return new global::Sample.Cache();
        }
    }
}
