//HintName: Sample.BaseInjectable_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class BaseInjectable_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding prop_TheDude = null!;

        public BaseInjectable_CompiledBinding()
            : base("Sample.BaseInjectable", "members/Sample.BaseInjectable", false, typeof(global::Sample.BaseInjectable))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            this.prop_TheDude = resolver.RequestBinding("Sample.Dude", "Sample.BaseInjectable.TheDude", true, false)!;
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            propertyDependencies.Add(this.prop_TheDude);
        }

        public override void InjectProperties(object target)
        {
            var inject = (global::Sample.BaseInjectable)target;
            inject.TheDude = (global::Sample.Dude)this.prop_TheDude.Get();
        }

        public override object Get()
        {
            var result = new global::Sample.BaseInjectable();
            this.InjectProperties(result);
            return result;
        }
    }
}
