//HintName: Sample.NeedsProperty_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class NeedsProperty_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding prop_Dependency = null!;

        public NeedsProperty_CompiledBinding()
            : base("Sample.NeedsProperty", "members/Sample.NeedsProperty", false, typeof(global::Sample.NeedsProperty))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            this.prop_Dependency = resolver.RequestBinding("Sample.Dep", "Sample.NeedsProperty.Dependency", true, false);
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            propertyDependencies.Add(this.prop_Dependency);
        }

        public override void InjectProperties(object target)
        {
            var inject = (global::Sample.NeedsProperty)target;
            inject.Dependency = (global::Sample.Dep)this.prop_Dependency.Get();
        }

        public override object Get()
        {
            var result = new global::Sample.NeedsProperty();
            this.InjectProperties(result);
            return result;
        }
    }
}
