//HintName: Sample.Endpoint_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Endpoint_CompiledBinding : global::Stiletto.Internal.Binding
    {
        public Endpoint_CompiledBinding()
            : base("Sample.Endpoint", "members/Sample.Endpoint", false, typeof(global::Sample.Endpoint))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
        }

        public override object Get()
        {
            return new global::Sample.Endpoint();
        }
    }
}
