//HintName: Sample.Derived_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Derived_CompiledBinding : global::Stiletto.Internal.Binding
    {
        public Derived_CompiledBinding()
            : base("Sample.Derived", "members/Sample.Derived", false, typeof(global::Sample.Derived))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
        }

        public override object Get()
        {
            return new global::Sample.Derived();
        }
    }
}
