//HintName: Sample.Bean_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Bean_CompiledBinding : global::Stiletto.Internal.Binding
    {
        public Bean_CompiledBinding()
            : base("Sample.Bean", "members/Sample.Bean", false, typeof(global::Sample.Bean))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
        }

        public override object Get()
        {
            return new global::Sample.Bean();
        }
    }
}
