//HintName: Sample.CoffeeMaker_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class CoffeeMaker_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding[] ctorParamBindings = null!;
        private global::Stiletto.Internal.Binding prop_Pump = null!;

        public CoffeeMaker_CompiledBinding()
            : base("Sample.CoffeeMaker", "members/Sample.CoffeeMaker", false, typeof(global::Sample.CoffeeMaker))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            var bindings = new global::Stiletto.Internal.Binding[1];
            bindings[0] = resolver.RequestBinding("Sample.Heater", "Sample.CoffeeMaker::.ctor", true, true);
            this.ctorParamBindings = bindings;
            this.prop_Pump = resolver.RequestBinding("Sample.Pump", "Sample.CoffeeMaker.Pump", true, false);
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            injectDependencies.UnionWith(this.ctorParamBindings);
            propertyDependencies.Add(this.prop_Pump);
        }

        public override void InjectProperties(object target)
        {
            var inject = (global::Sample.CoffeeMaker)target;
            inject.Pump = (global::Sample.Pump)this.prop_Pump.Get();
        }

        public override object Get()
        {
            var result = new global::Sample.CoffeeMaker(
                (global::Sample.Heater)this.ctorParamBindings[0].Get()
            );
            this.InjectProperties(result);
            return result;
        }
    }
}
