//HintName: Sample.Service_CompiledBinding.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class Service_CompiledBinding : global::Stiletto.Internal.Binding
    {
        private global::Stiletto.Internal.Binding prop_Endpoint = null!;

        public Service_CompiledBinding()
            : base("Sample.Service", "members/Sample.Service", false, typeof(global::Sample.Service))
        {
        }

        public override void Resolve(global::Stiletto.Internal.Resolver resolver)
        {
            this.prop_Endpoint = resolver.RequestBinding("@primary/Sample.Endpoint", "Sample.Service.Endpoint", true, false)!;
        }

        public override void GetDependencies(
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
            global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
        {
            propertyDependencies.Add(this.prop_Endpoint);
        }

        public override void InjectProperties(object target)
        {
            var inject = (global::Sample.Service)target;
            inject.Endpoint = (global::Sample.Endpoint)this.prop_Endpoint.Get();
        }

        public override object Get()
        {
            var result = new global::Sample.Service();
            this.InjectProperties(result);
            return result;
        }
    }
}
