//HintName: Sample.DripCoffeeModule_CompiledModule.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class DripCoffeeModule_CompiledModule : global::Stiletto.Internal.RuntimeModule
    {
        public DripCoffeeModule_CompiledModule()
            : base(
                typeof(global::Sample.DripCoffeeModule),
                new string[] { "members/Sample.Heater" },
                new global::System.Type[] {  },
                true,
                true,
                false)
        {
        }

        public override object CreateModule()
        {
            return new global::Sample.DripCoffeeModule();
        }

        public override void GetBindings(global::System.Collections.Generic.IDictionary<string, global::Stiletto.Internal.Binding> bindings)
        {
            var module = (global::Sample.DripCoffeeModule)this.Module;
            bindings.Add("Sample.Heater", new ProviderBinding_0(module));
            bindings.Add("@main/Sample.Pump", new ProviderBinding_1(module));
            bindings.Add("System.String", new ProviderBinding_2(module));
        }

        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private sealed class ProviderBinding_0 : global::Stiletto.Internal.Binding
        {
            private readonly global::Sample.DripCoffeeModule module;

            public ProviderBinding_0(global::Sample.DripCoffeeModule module)
                : base("Sample.Heater", null, false, "Sample.DripCoffeeModule.ProvideHeater")
            {
                this.module = module;
                this.IsLibrary = true;
            }

            public override object Get()
            {
                return this.module.ProvideHeater();
            }
        }

        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private sealed class ProviderBinding_1 : global::Stiletto.Internal.Binding
        {
            private readonly global::Sample.DripCoffeeModule module;
            private global::Stiletto.Internal.Binding arg0 = null!;

            public ProviderBinding_1(global::Sample.DripCoffeeModule module)
                : base("@main/Sample.Pump", null, false, "Sample.DripCoffeeModule.ProvidePump")
            {
                this.module = module;
                this.IsLibrary = true;
            }

            public override void Resolve(global::Stiletto.Internal.Resolver resolver)
            {
                this.arg0 = resolver.RequestBinding("Sample.Heater", typeof(global::Sample.DripCoffeeModule), true, true)!;
            }

            public override void GetDependencies(
                global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> injectDependencies,
                global::System.Collections.Generic.ISet<global::Stiletto.Internal.Binding> propertyDependencies)
            {
                injectDependencies.Add(this.arg0);
            }

            public override object Get()
            {
                return this.module.ProvidePump(
                    (global::Sample.Heater)this.arg0.Get()
                );
            }
        }

        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private sealed class ProviderBinding_2 : global::Stiletto.Internal.Binding
        {
            private readonly global::Sample.DripCoffeeModule module;

            public ProviderBinding_2(global::Sample.DripCoffeeModule module)
                : base("System.String", null, true, "Sample.DripCoffeeModule.Brand")
            {
                this.module = module;
                this.IsLibrary = true;
            }

            public override object Get()
            {
                return this.module.Brand();
            }
        }
    }
}
