//HintName: Sample.AggregateModule_CompiledModule.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class AggregateModule_CompiledModule : global::Stiletto.Internal.RuntimeModule
    {
        public AggregateModule_CompiledModule()
            : base(
                typeof(global::Sample.AggregateModule),
                new string[] {  },
                new global::System.Type[] { typeof(global::Sample.OtherModule) },
                true,
                false,
                false)
        {
        }

        public override object CreateModule()
        {
            return new global::Sample.AggregateModule();
        }

        public override void GetBindings(global::System.Collections.Generic.IDictionary<string, global::Stiletto.Internal.Binding> bindings)
        {
        }
    }
}
