//HintName: Sample.LogModule_CompiledModule.g.cs
// <auto-generated/>
#nullable enable
namespace Sample
{
    [global::System.CodeDom.Compiler.GeneratedCode("Stiletto.Generator", null)]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    internal sealed class LogModule_CompiledModule : global::Stiletto.Internal.RuntimeModule
    {
        public LogModule_CompiledModule()
            : base(
                typeof(global::Sample.LogModule),
                new string[] {  },
                new global::System.Type[] {  },
                true,
                false,
                false)
        {
        }

        public override object CreateModule()
        {
            return new global::Sample.LogModule();
        }

        public override void GetBindings(global::System.Collections.Generic.IDictionary<string, global::Stiletto.Internal.Binding> bindings)
        {
            var module = (global::Sample.LogModule)this.Module;
            global::Stiletto.Internal.Loaders.Codegen.SetBindings.Add<string>(bindings, "System.Collections.Generic.ISet`1<System.String>", new ProviderBinding_0(module));
            global::Stiletto.Internal.Loaders.Codegen.SetBindings.Add<string>(bindings, "System.Collections.Generic.ISet`1<System.String>", new ProviderBinding_1(module));
        }

        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private sealed class ProviderBinding_0 : global::Stiletto.Internal.Binding
        {
            private readonly global::Sample.LogModule module;

            public ProviderBinding_0(global::Sample.LogModule module)
                : base("System.String", null, false, "Sample.LogModule.ConsoleSink")
            {
                this.module = module;
            }

            public override object Get()
            {
                return this.module.ConsoleSink();
            }
        }

        [global::System.Runtime.CompilerServices.CompilerGenerated]
        private sealed class ProviderBinding_1 : global::Stiletto.Internal.Binding
        {
            private readonly global::Sample.LogModule module;

            public ProviderBinding_1(global::Sample.LogModule module)
                : base("System.String", null, false, "Sample.LogModule.FileSink")
            {
                this.module = module;
            }

            public override object Get()
            {
                return this.module.FileSink();
            }
        }
    }
}
