using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Stiletto.Generator
{
    /// <summary>
    /// The single Stiletto source generator. Emits per-type inject bindings, per-module
    /// compiled modules, and — from the collected models — one aggregated
    /// <c>Stiletto.Generated.CompiledLoader</c> per assembly plus a
    /// <c>[ModuleInitializer]</c> that registers it with <c>Stiletto.LoaderRegistry</c>.
    /// The client experience is unchanged (<c>Container.Create(typeof(Module))</c>);
    /// registration is automatic and needs no <see cref="System.AppDomain"/> scanning.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class StilettoGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var injectModels = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    InjectBindingEmitter.InjectAttributeMetadataName,
                    predicate: static (node, _) => node is ConstructorDeclarationSyntax or PropertyDeclarationSyntax,
                    transform: static (ctx, _) => InjectBindingEmitter.BuildModel(ctx.TargetSymbol.ContainingType))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!)
                .Collect();

            var moduleModels = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    ModuleEmitter.ModuleAttributeMetadataName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => ModuleEmitter.BuildModel((INamedTypeSymbol)ctx.TargetSymbol))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!)
                .Collect();

            context.RegisterSourceOutput(injectModels, static (spc, models) =>
            {
                // A type with both an [Inject] ctor and [Inject] properties fires
                // multiple times, producing identical models; emit each once.
                var seen = new HashSet<string>();
                foreach (var model in models)
                {
                    if (seen.Add(model.HintName))
                    {
                        spc.AddSource(model.HintName, InjectBindingEmitter.Emit(model));
                    }
                }
            });

            context.RegisterSourceOutput(moduleModels, static (spc, models) =>
            {
                var seen = new HashSet<string>();
                foreach (var model in models)
                {
                    if (seen.Add(model.HintName))
                    {
                        spc.AddSource(model.HintName, ModuleEmitter.Emit(model));
                    }
                }
            });

            context.RegisterSourceOutput(injectModels.Combine(moduleModels), static (spc, pair) =>
                EmitLoader(spc, pair.Left, pair.Right));
        }

        private static void EmitLoader(
            SourceProductionContext spc,
            ImmutableArray<InjectBindingModel> injectModels,
            ImmutableArray<ModuleModel> moduleModels)
        {
            if (injectModels.IsEmpty && moduleModels.IsEmpty)
            {
                // Nothing compiled in this assembly — no loader, no registration.
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Stiletto.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"Stiletto.Generator\", null)]");
            sb.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
            sb.AppendLine("    internal sealed class CompiledLoader : global::Stiletto.Internal.ILoader");
            sb.AppendLine("    {");

            // GetInjectBinding: className -> new {Type}_CompiledBinding()
            sb.AppendLine("        public global::Stiletto.Internal.Binding GetInjectBinding(string key, string className, bool mustBeInjectable)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (className)");
            sb.AppendLine("            {");
            var seenInject = new HashSet<string>();
            foreach (var model in injectModels)
            {
                if (seenInject.Add(model.Key))
                {
                    sb.Append("                case ").Append(Literal(model.Key)).Append(": return new ")
                      .Append(GlobalName(model.Namespace, model.BindingTypeName)).AppendLine("();");
                }
            }
            sb.AppendLine("                default: return null!;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // GetRuntimeModule: moduleType.FullName -> new {Module}_CompiledModule()
            sb.AppendLine("        public global::Stiletto.Internal.RuntimeModule GetRuntimeModule(global::System.Type moduleType, object moduleInstance)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (moduleType.FullName)");
            sb.AppendLine("            {");
            var seenModule = new HashSet<string>();
            foreach (var model in moduleModels)
            {
                if (seenModule.Add(model.ReflectionName))
                {
                    sb.Append("                case ").Append(Literal(model.ReflectionName)).Append(": return new ")
                      .Append(GlobalName(model.Namespace, model.CompiledTypeName)).AppendLine("();");
                }
            }
            sb.AppendLine("                default: return null!;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Lazy / IProvider are Phase 2 — fall through to the reflection fallback for now.
            sb.AppendLine("        public global::Stiletto.Internal.Binding GetLazyInjectBinding(string key, object requiredBy, string lazyKey) => null!;");
            sb.AppendLine("        public global::Stiletto.Internal.Binding GetIProviderInjectBinding(string key, object requiredBy, bool mustBeInjectable, string providerKey) => null!;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
            sb.AppendLine("    internal static class CompiledLoaderRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void Register() => global::Stiletto.LoaderRegistry.Register(new CompiledLoader());");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("Stiletto.Generated.CompiledLoader.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string GlobalName(string? ns, string typeName)
            => ns is null ? "global::" + typeName : "global::" + ns + "." + typeName;

        private static string Literal(string value)
            => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
