// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Abra.Compiler.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Abra.Compiler;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class InjectBinding : InjectBindingBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nnamespace ");
            
            #line 10 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    using Binding = global::Abra.Internal.Binding;\r\n    using Resolver = glo" +
                    "bal::Abra.Internal.Resolver;\r\n\r\n    /// <summary>\r\n    /// Represents a binding " +
                    "to an object of type <see cref=\"");
            
            #line 16 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.FullName));
            
            #line default
            #line hidden
            this.Write("\"/>.\r\n    /// </summary>\r\n");
            
            #line 18 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.IsEntryPoint) { 
            
            #line default
            #line hidden
            this.Write("    /// <remarks>\r\n    /// ");
            
            #line 20 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.LiteralName));
            
            #line default
            #line hidden
            this.Write(" is an entry point binding.\r\n    /// </remarks>\r\n");
            
            #line 22 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 23 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.AccessModifier));
            
            #line default
            #line hidden
            this.Write(" class ");
            
            #line 23 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BindingName(cls.LiteralName)));
            
            #line default
            #line hidden
            this.Write("_CompiledBinding : Binding\r\n    {\r\n");
            
            #line 25 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.InjectableProperties.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("        // Property bindings\r\n");
            
            #line 27 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 foreach (var prop in cls.InjectableProperties) { 
            
            #line default
            #line hidden
            this.Write("        private Binding ");
            
            #line 28 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 29 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            
            #line 30 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.BaseTypeKey != null) { 
            
            #line default
            #line hidden
            this.Write("        private Binding baseTypeBinding;\r\n");
            
            #line 33 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.CtorParameters.Count != 0) { 
            
            #line default
            #line hidden
            this.Write("        // Constructor bindings\r\n        private Binding[] ctorParameterBindings " +
                    "= new Binding[");
            
            #line 36 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.CtorParameters.Count));
            
            #line default
            #line hidden
            this.Write("];\r\n");
            
            #line 37 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        public ");
            
            #line 39 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BindingName(cls.LiteralName)));
            
            #line default
            #line hidden
            this.Write("_CompiledBinding()\r\n            : base(\"");
            
            #line 40 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.Key));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 40 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.MemberKey));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 40 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.IsSingleton ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 40 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.Type.ReflectionName));
            
            #line default
            #line hidden
            this.Write("\")\r\n        {\r\n        }\r\n\r\n        public override void Resolve(Resolver resolve" +
                    "r)\r\n        {\r\n");
            
            #line 46 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 foreach (var prop in cls.InjectableProperties) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 47 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" = resolver.RequestBinding(\"");
            
            #line 47 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Key));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 47 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 48 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 for (var i = 0; i < cls.CtorParameters.Count; ++i) { 
            
            #line default
            #line hidden
            this.Write("            ctorParameterBindings[");
            
            #line 50 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("] = resolver.RequestBinding(\"");
            
            #line 50 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.CtorParameters[i].Key));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 50 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.InjectableConstructor.FullName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 51 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            
            #line 52 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.BaseTypeKey != null) { 
            
            #line default
            #line hidden
            this.Write("            baseTypeBinding = resolver.RequestBinding(\"");
            
            #line 53 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.BaseTypeKey));
            
            #line default
            #line hidden
            this.Write("\", this, false);\r\n");
            
            #line 54 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public override void GetDependencies(ISet<Binding> injectDep" +
                    "endencies, ISet<Binding> propDependencies)\r\n        {\r\n");
            
            #line 59 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.CtorParameters.Count != 0) { 
            
            #line default
            #line hidden
            this.Write("            injectDependencies.UnionWith(ctorParameterBindings);\r\n");
            
            #line 61 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            
            #line 62 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 foreach (var prop in cls.InjectableProperties) { 
            
            #line default
            #line hidden
            this.Write("            propDependencies.Add(");
            
            #line 63 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 64 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            
            #line 65 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.BaseTypeKey != null) { 
            
            #line default
            #line hidden
            this.Write("            propDependencies.Add(baseTypeBinding);\r\n");
            
            #line 67 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public override object Get()\r\n        {\r\n");
            
            #line 72 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.CtorParameters.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("            var obj = new ");
            
            #line 73 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.FullName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 74 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            var obj = new ");
            
            #line 75 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.FullName));
            
            #line default
            #line hidden
            this.Write("(\r\n");
            
            #line 76 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 for (var i = 0; i < cls.CtorParameters.Count; ++i) { 
            
            #line default
            #line hidden
            this.Write("                (");
            
            #line 77 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.CtorParameters[i].TypeName));
            
            #line default
            #line hidden
            this.Write(") ctorParameterBindings[");
            
            #line 77 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("].Get() ");
            
            #line 77 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i == cls.CtorParameters.Count - 1 ? ");" : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 78 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } //foreach 
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } //if 
            
            #line default
            #line hidden
            this.Write("            InjectProperties(obj);\r\n            return obj;\r\n        }\r\n\r\n       " +
                    " public override void InjectProperties(object obj)\r\n        {\r\n");
            
            #line 86 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.InjectableProperties.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("            var toInject = (");
            
            #line 87 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(cls.FullName));
            
            #line default
            #line hidden
            this.Write(") obj;\r\n");
            
            #line 88 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 foreach (var prop in cls.InjectableProperties) { 
            
            #line default
            #line hidden
            this.Write("            toInject.");
            
            #line 89 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(" = (");
            
            #line 89 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.TypeName));
            
            #line default
            #line hidden
            this.Write(") ");
            
            #line 89 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(".Get();\r\n");
            
            #line 90 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } //foreach 
            
            #line default
            #line hidden
            
            #line 91 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } //if 
            
            #line default
            #line hidden
            
            #line 92 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 if (cls.BaseTypeKey != null) { 
            
            #line default
            #line hidden
            this.Write("            baseTypeBinding.InjectProperties(obj);\r\n");
            
            #line 94 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 98 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"

protected string BindingName(string id)
{
    return id.Replace(".", "_");
}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\ben\Development\abra-ioc\Abra.Compiler\Templates\InjectBinding.tt"

private global::Abra.Compiler.Generators.InjectBindingGenerator _clsField;

/// <summary>
/// Access the cls parameter of the template.
/// </summary>
private global::Abra.Compiler.Generators.InjectBindingGenerator cls
{
    get
    {
        return this._clsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool clsValueAcquired = false;
if (this.Session.ContainsKey("cls"))
{
    if ((typeof(global::Abra.Compiler.Generators.InjectBindingGenerator).IsAssignableFrom(this.Session["cls"].GetType()) == false))
    {
        this.Error("The type \'Abra.Compiler.Generators.InjectBindingGenerator\' of the parameter \'cls\'" +
                " did not match the type of the data passed to the template.");
    }
    else
    {
        this._clsField = ((global::Abra.Compiler.Generators.InjectBindingGenerator)(this.Session["cls"]));
        clsValueAcquired = true;
    }
}
if ((clsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("cls");
    if ((data != null))
    {
        if ((typeof(global::Abra.Compiler.Generators.InjectBindingGenerator).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'Abra.Compiler.Generators.InjectBindingGenerator\' of the parameter \'cls\'" +
                    " did not match the type of the data passed to the template.");
        }
        else
        {
            this._clsField = ((global::Abra.Compiler.Generators.InjectBindingGenerator)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class InjectBindingBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
