using System;
using System.IO;

namespace Abra.Compiler
{
    class Program
    {
        private static Settings settings;

        static int Main(string[] args)
        {
#if DEBUG
            if (args.Length == 0) {
                args = new[] { "-p", @"C:\Users\ben\Development\abra-ioc\Abra.Test\Abra.Test.csproj"};
            }
#endif

            try {
                settings = new Settings(args);
            }
            catch (Exception ex) {
                Console.WriteLine(ex.Message);
                return -1;
            }

            // Truncate the output file if it currently exists, so we don't compile our generated code.
            settings.OutputFile.Open(FileMode.Create).Dispose();

            var errorReporter = new ErrorReporter();
            var compiler = new Compiler(settings.ProjectFile);

            using (var output = settings.OutputFile.CreateText()) {
                output.WriteLine(Preamble);
                compiler.Compile(output, errorReporter);
                output.Flush();
            }

            return 0;
        }

        private const string Preamble = @"///////////////
// Generated by TopHat - do not modify directly.
//

using System;
using System.Collections.Generic;";
    }
}
